#include <assert.h>
#include <stdio.h>
// #include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <alloca.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>

#define ALLOC malloc
#define ALLOC_PACKED ALLOC

#define SIZE 1000

// Big default:
static long long global_default_buf_size = (500lu * 1000lu * 1000lu);

static long long global_size_param = 1;
static long long global_iters_param = 1;

static char*     global_benchfile_param = NULL;


typedef char TagTyPacked;  // Must be consistent with codegen in Target.hs
typedef char TagTyBoxed;   // Must be consistent with codegen in Target.hs
typedef long long IntTy;
typedef IntTy SymTy;

typedef struct dict_item {
  struct dict_item * next;
  int key;
  union {
    int intval;
    void * ptrval;
  };
} dict_item_t;

dict_item_t * dict_alloc() {
  return ALLOC(sizeof(dict_item_t));
}

dict_item_t *dict_insert_int(dict_item_t *ptr, SymTy key, IntTy val) {
  dict_item_t *ret = dict_alloc();
  ret->key = key;
  ret->intval = val;
  ret->next = ptr;
  return ret;
}

IntTy dict_lookup_int(dict_item_t *ptr, SymTy key) {
  while (ptr != 0) {
    if (ptr->key == key) {
      return ptr->intval;
    } else {
      ptr = ptr->next;
    }
  }
  printf("Error, key %lld not found!\n",key);
  exit(1);
}

char* read_benchfile_param() {
  if (global_benchfile_param == NULL) {
    fprintf(stderr, "read_benchfile_param: benchmark input file was not set!\n");
    exit(1);
  } else
    return global_benchfile_param;
}

// Could try alloca() here.  Better yet, we could keep our own,
// separate stack and insert our own code to restore the pointer
// before any function that (may have) called ALLOC_SCOPED returns.

// #define ALLOC_SCOPED() alloca(1024)
#define ALLOC_SCOPED() alloca(100LU*1024LU)
// #define ALLOC_SCOPED() alloc_scoped()

// Stack allocation is either too small or blows our stack.
// We need a way to make a giant stack if we want to use alloca.
// #define ALLOC_SCOPED() ALLOC(global_default_buf_size)


// Our global pointer.  No parallelism.
// static char* stack_scoped_region;
// char* alloc_scoped() { return stack_scoped_region; }


// fun fact: __ prefix is actually reserved and this is an undefined behavior.
// These functions must be provided by the code generator.
void __main_expr();


void show_usage()
{

    printf("\nUSAGE\n");
    printf("This binary was generated by the Gibbon compiler.\n");
    printf("Options:\n");
    printf(" --buffer-size <bytes>      Set the buffer size (default %lld).\n", global_default_buf_size);
    printf(" --bench <size> <iters>     Run the file while setting these global benchmark params.\n");
    printf(" --bench-input <path>       Set the input file read for benchmarking. Applies only\n");
    printf("                            if the program was *compiled* with --bench. \n");
    return;
}

double avg(const double* arr, int n)
{
    double sum = 0.0;
    for(int i=0; i<n; i++) sum += arr[i];
    return sum / (double)n;
}

double difftimespecs(struct timespec* t0, struct timespec* t1)
{
    return (double)(t1->tv_sec - t0->tv_sec)
      + ((double)(t1->tv_nsec - t0->tv_nsec) / 1000000000.0);
}

int compare_doubles(const void *a, const void *b)
{
    const double *da = (const double *) a;
    const double *db = (const double *) b;
    return (*da > *db) - (*da < *db);
}


int main(int argc, char** argv)
{
    // parameters to parse:
    //
    //   num iterations: How many times to repeat a benchmark. 
    //   tree size: An integer passes to `build_tree()`. 

    struct rlimit lim;
    int code;
    if ( (code = getrlimit(RLIMIT_STACK, &lim)) ) {
      fprintf(stderr, " [gibbon rts] failed to getrlimit, code %d\n", code);
      abort();
    }
    
    // lim.rlim_cur = 1024LU * 1024LU * 1024LU; // 1GB stack.
    lim.rlim_cur = 512LU * 1024LU * 1024LU; // 500MB stack.
    // lim.rlim_max = lim.rlim_cur; // Normal users may only be able to decrease this.

    // WARNING: Haven't yet figured out why this doesn't work on MacOS...
    #ifndef __APPLE__
    code = setrlimit(RLIMIT_STACK, &lim);    
    while (code) {
      fprintf(stderr, " [gibbon rts] Failed to set stack size to %llu, code %d\n", (unsigned long long)lim.rlim_cur, code);
      lim.rlim_cur /= 2;
      // lim.rlim_max /= 2;
      if(lim.rlim_cur < 100 * 1024) {
        fprintf(stderr, " [gibbon rts] Failed setrlimit stack size to something reasonable; giving up.\n");
        abort();
      }
      int code = setrlimit(RLIMIT_STACK, &lim);    
    }
    #endif
    
    // TODO: atoi() error checking
    
    for (int i = 1; i < argc; ++i)
    {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
          show_usage();
          exit(0);
        }
        else if (strcmp(argv[i], "--buffer-size") == 0 && i < argc - 1)
        {
            global_default_buf_size = atoll(argv[i + 1]);
            i++;
        }
        else if ((strcmp(argv[i], "--benchmark") == 0) || (strcmp(argv[i], "--bench") == 0))
        {
          // benchmark = 1;
          if (i+2 >= argc) {
            fprintf(stderr, "Not enough arguments after -benchmark, expected <size> <iters>.\n");
            show_usage();
            exit(1);
          }
          // In this mode, we expect the last two arguments to be 
          global_size_param  = atoll(argv[i + 1]);
          global_iters_param = atoll(argv[i + 2]);
          i += 2;
        }
        else if ((strcmp(argv[i], "--bench-input") == 0)) {
	  if (i+1 >= argc) {
            fprintf(stderr, "Not enough arguments after -file, expected <file>.\n");
            show_usage();
            exit(1);
          }
	  global_benchfile_param = argv[i+1];
	  i++;
	}
	else
        {
            fprintf(stderr, "Can't parse argument: \"%s\"\n", argv[i]);
            show_usage();
            exit(1);
        }
    }
    
    __main_expr();

    return 0;
}
