(let ([a 42])
  (let ([b a])
    (let ([c b])
      (let ([d c])
        (let ([e d])
          (let ([f e])
            (let ([g f])
              (let ([h g])
                (let ([i h])
                  (let ([j i])
                    (let ([k j])
                      (let ([l k])
                        (let ([m l])
                          (let ([n m])
                            (let ([o n])
                              (let ([p o])
                                (let ([q p])
                                  (let ([r q])
                                    (let ([s r])
                                      r)))))))))))))))))))
      
