// The imports here must be kept in sync with
// 'hashIncludes' in Gibbon.Passes.Codegen.

#include "gibbon.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <math.h>
#include <stdbool.h>
#include <string.h>
#include <time.h>
#include <alloca.h>
#include <sys/mman.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdarg.h>
#include <errno.h>
#include <uthash.h>

#ifdef _WIN64
#include <windows.h>
#endif

#ifdef _POINTER
#include <gc.h>
#endif

#ifdef _PARALLEL
#include <cilk/cilk.h>
#include <cilk/cilk_api.h>
#endif


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Common Globals
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

// Chunk sizes of buffers, see GitHub #79 and #110.

long long gib_global_biginf_init_chunk_size = (4 * GB);
long long gib_global_inf_init_chunk_size = 1 * KB;
long long gib_global_max_chunk_size = (1 * GB);

// Runtime arguments, values updated by the flags parser.
GibInt gib_global_size_param = 1;
GibInt gib_global_iters_param = 1;
char *gib_global_bench_prog_param = NULL;
char *gib_global_benchfile_param = NULL;
char *gib_global_arrayfile_param = NULL;
long long gib_global_arrayfile_length_param = -1;

// Number of regions allocated.
long long gib_global_region_count = 0;

// Invariant: should always be equal to max(sym_table_keys)
GibSym gib_global_gensym_counter = 0;


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Helpers
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

char *gib_read_benchfile_param()
{
    if (gib_global_benchfile_param == NULL) {
        fprintf(stderr, "gib_read_benchfile_param: benchmark input file was not set! Set using --bench-input.\n");
        exit(1);
    } else
        return gib_global_benchfile_param;
}

char *gib_read_arrayfile_param()
{
    if (gib_global_arrayfile_param == NULL) {
        fprintf(stderr, "gib_read_arrayfile_param: array input file was not set! Set using --array-input.\n");
        exit(1);
    } else
        return gib_global_arrayfile_param;
}

long long gib_read_arrayfile_length_param()
{
    if (gib_global_arrayfile_length_param == -1) {
        fprintf(stderr, "gib_read_arrayfile_length_param: array input file length was not set! Set using --array-input-length.\n");
        exit(1);
    } else
        return gib_global_arrayfile_length_param;
}


void gib_show_usage(char** argv) {
    printf("\n");
    printf("This binary was generated by the Gibbon compiler.\n");
    printf("\n");
    printf("Usage: %s [OPTS] [size] [iters]\n", argv[0]);

    printf("\n");
    printf("Options:\n");
    printf(" --buffer-size <bytes>      Set the buffer size (default %lld).\n", gib_global_biginf_init_chunk_size);
    printf(" --bench-input <path>       Set the input file read for benchmarking. Applies only\n");
    printf("                            IF the program was *compiled* with --bench-fun. \n");
    return;
}

double gib_avg(const double* arr, int n)
{
    double sum = 0.0;
    for(int i=0; i<n; i++) sum += arr[i];
    return sum / (double)n;
}

double gib_difftimespecs(struct timespec* t0, struct timespec* t1)
{
    return (double)(t1->tv_sec - t0->tv_sec)
            + ((double)(t1->tv_nsec - t0->tv_nsec) / 1000000000.0);
}

int gib_compare_doubles(const void *a, const void *b)
{
    const double *da = (const double *) a;
    const double *db = (const double *) b;
    return (*da > *db) - (*da < *db);
}

// Exponentiation
GibInt gib_expll(GibInt base, GibInt pow)
{
    if (base == 2) {
        return (1 << pow);
    } else {
        GibInt i, result = 1;
        for (i = 0; i < pow; i++)
            result *= base;
        return result;
    }
}

// https://www.cprogramming.com/snippets/source-code/find-the-number-of-cpu-cores-for-windows-mac-or-linux
inline GibInt gib_get_num_processors()
{
#ifdef _WIN64
    SYSTEM_INFO sysinfo;
    GetSystemInfo(&sysinfo);
    return sysinfo.dwNumberOfProcessors;
#else
    return sysconf(_SC_NPROCESSORS_ONLN);
#endif
}

// Requires -std=gnu11
int dbgprintf(const char *format, ...)
{
    int code = 0;
    va_list args;
    va_start(args, format);
#ifdef _DEBUG
    code = vprintf(format, args);
#endif
    va_end(args);
    return code;
}


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Allocators
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */



/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Bump allocation for linked-lists
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */


#ifdef _BUMPALLOC
// #define _DEBUG
#warning "Using bump allocator."

__thread char *gib_global_bumpalloc_heap_ptr = (char*)NULL;
__thread char *gib_global_bumpalloc_heap_ptr_end = (char*)NULL;
char *gib_global_saved_heap_ptr_stack[100];
int gib_global_num_saved_heap_ptr = 0;

// For simplicity just use a single large slab:
inline void gib_init_bumpalloc()
{
    gib_global_bumpalloc_heap_ptr = (char*)malloc(gib_global_biginf_init_chunk_size);
    gib_global_bumpalloc_heap_ptr_end = gib_global_bumpalloc_heap_ptr + gib_global_biginf_init_chunk_size;
#ifdef _DEBUG
    printf("Arena size for bump alloc: %lld\n", gib_global_biginf_init_chunk_size);
    printf("gib_bumpalloc/gib_init_bumpalloc DONE: heap_ptr = %p\n", gib_global_bumpalloc_heap_ptr);
#endif
}

void *gib_bumpalloc(long long n)
{
    if (! gib_global_bumpalloc_heap_ptr) {
        gib_init_bumpalloc();
    }
    if (gib_global_bumpalloc_heap_ptr + n < gib_global_bumpalloc_heap_ptr_end) {
        char* old= gib_global_bumpalloc_heap_ptr;
        gib_global_bumpalloc_heap_ptr += n;
        return old;
    } else {
        fprintf(stderr, "Warning: bump allocator ran out of memory.");
        exit(1);
    }
}

// Snapshot the current heap pointer value across all threads.
void gib_save_alloc_state()
{
#ifdef _DEBUG
    printf("Saving(%p): pos %d", heap_ptr, gib_global_num_saved_heap_ptr);
#endif
    gib_global_saved_heap_ptr_stack[gib_global_num_saved_heap_ptr] = heap_ptr;
    gib_global_num_saved_heap_ptr++;
#ifdef _DEBUG
    printf("\n");
#endif
}

void gib_restore_alloc_state()
{
    if(gib_global_num_saved_heap_ptr <= 0) {
        fprintf(stderr, "Bad call to gib_restore_alloc_state!  Saved stack empty!\ne");
        exit(1);
    }
    gib_global_num_saved_heap_ptr--;
#ifdef _DEBUG
    printf("Restoring(%p): pos %d, discarding %p",
           gib_global_saved_heap_ptr_stack[gib_global_num_saved_heap_ptr], gib_global_num_saved_heap_ptr, gib_global_bumpalloc_heap_ptr);
#endif
    gib_global_bumpalloc_heap_ptr = gib_global_saved_heap_ptr_stack[gib_global_num_saved_heap_ptr];
}

#else
// Regular malloc mode:
void gib_init_bumpalloc() {}
void *gib_bumpalloc(long long n) { return malloc(n); }
void gib_save_alloc_state() {}
void gib_restore_alloc_state() {}

#endif // BUMPALLOC


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Bump allocated nursery for regions.
 * See GitHub #122.
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

__thread char *gib_global_nursery_heap_ptr = (char*)NULL;
__thread char *gib_global_nursery_heap_ptr_end = (char*)NULL;

void gib_init_nursery()
{
    gib_global_nursery_heap_ptr = (char*)malloc(NURSERY_SIZE);
    if (gib_global_nursery_heap_ptr == NULL) {
        printf("init_region: malloc failed: %d", NURSERY_SIZE);
        exit(1);
    }
    gib_global_nursery_heap_ptr_end = gib_global_nursery_heap_ptr + NURSERY_SIZE;
#ifdef _DEBUG
    printf("gib_init_nursery: DONE, heap_ptr = %p\n", gib_global_nursery_heap_ptr);
#endif
}

void *gib_alloc_in_nursery(long long n)
{
    if (! gib_global_nursery_heap_ptr) {
        gib_init_nursery();
    }
    if (gib_global_nursery_heap_ptr + n < gib_global_nursery_heap_ptr_end) {
        char* old = gib_global_nursery_heap_ptr;
        gib_global_nursery_heap_ptr += n;
#ifdef _DEBUG
        printf("gib_alloc_in_nursery: DONE, %lld\n", n);
#endif
        return old;
    } else {
        return NULL;
    }
}


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Various allocators
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */


/*
 * If parallelism is enabled, we always use a nursery/malloc based allocator
 * since Boehm GC is not thread-safe in its default configuration. It can be
 * made thread-safe by building it with appropriate flags, but we don't do that.
 * Presently, all parallel pointer-based programs will leak memory.
 */

#ifdef _POINTER
#ifndef _PARALLEL
inline void *gib_alloc(size_t n) { return GC_MALLOC(n); }
inline void *gib_small_alloc(size_t n) { return GC_MALLOC(n); }
#else
inline void *gib_alloc(size_t n) { return malloc(n); }
inline void *gib_small_alloc(size_t n) { return gib_alloc_in_nursery(n); }
#endif // ifndef _PARALLEL
#else
inline void *gib_alloc(size_t n) { return malloc(n); }
inline void *gib_small_alloc(size_t n) { return gib_alloc_in_nursery(n); }
#endif // ifdef _POINTER

inline void *gib_counted_alloc(size_t n) {
    gib_bump_global_region_count();
    return gib_alloc(n);
}

// Could try alloca() here.  Better yet, we could keep our own,
// separate stack and insert our own code to restore the pointer
// before any function that (may have) called gib_scoped_alloc returns.
inline void *gib_scoped_alloc(size_t n) { return alloca(n); }

// Stack allocation is either too small or blows our stack.
// We need a way to make a giant stack if we want to use alloca.

// Our global pointer.  No parallelism.
// static char* stack_scoped_region;
// char* alloc_scoped() { return stack_scoped_region; }



/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Arenas
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

inline GibArena *gib_alloc_arena()
{
    GibArena *ar = gib_alloc(sizeof(GibArena));
    ar->ind = 0;
    ar->mem = gib_alloc(gib_global_max_chunk_size);
    ar->reflist = 0;
    return ar;
}

inline void gib_free_arena(GibArena *ar)
{
    free(ar->mem);
    // TODO(vollmerm): free everything in ar->reflist
    free(ar);
}

inline GibCursor gib_extend_arena(GibArena *ar, int size)
{
    GibCursor ret = ar->mem + ar->ind;
    ar->ind += size;
    return ret;
}

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Arena-based dictionaries
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */


inline GibSymDict *gib_dict_alloc(GibArena *ar)
{
    return (GibSymDict *) gib_extend_arena(ar, sizeof(GibSymDict)); // gib_alloc(sizeof(GibSymDict));
}

inline GibSymDict *gib_dict_insert_ptr(GibArena *ar, GibSymDict *ptr, GibSym key, GibPtr val)
{
    GibSymDict *ret = gib_dict_alloc(ar);
    ret->key = key;
    ret->ptrval = val;
    ret->next = ptr;
    return ret;
}

inline GibPtr gib_dict_lookup_ptr(GibSymDict *ptr, GibSym key)
{
    while (ptr != 0) {
        if (ptr->key == key) {
            return ptr->ptrval;
        } else {
            ptr = ptr->next;
        }
    }
    printf("Error, key %lld not found!\n",key);
    exit(1);
}

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Sets
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */


inline GibSymSet *gib_empty_set()
{
    return NULL;
}

inline GibSymSet *gib_insert_set(GibSymSet *set, int sym)
{
    GibSymSet *s;
    HASH_FIND_INT(set, &sym, s);  /* sym already in the hash? */
    if (s==NULL) {
        s = gib_alloc(sizeof(GibSymSet));
        s->val = sym;
        HASH_ADD_INT(set,val,s);
    }
    return set;
}

inline GibBool gib_contains_set(GibSymSet *set, int sym)
{
    GibSymSet *s;
    HASH_FIND_INT(set, &sym, s);
    return (s!=NULL);
}

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Sym Hash
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */


inline GibSymHash *gib_empty_hash()
{
    return NULL;
}

inline GibSymHash *gib_insert_hash(GibSymHash *hash, int k, int v)
{
    GibSymHash *s;
    // NOTE: not checking for duplicates!
    s = gib_alloc(sizeof(GibSymHash));
    s->val = v;
    s->key = k;
    HASH_ADD_INT(hash,key,s);

    return hash;
}

inline GibSym gib_lookup_hash(GibSymHash *hash, int k)
{
    GibSymHash *s;
    HASH_FIND_INT(hash,&k,s);
    if (s==NULL) {
        return k; // NOTE: return original key if val not found
        // TODO(vollmerm): come up with something better to do here
    } else {
        return s->val;
    }
}

inline GibBool gib_contains_hash(GibSymHash *hash, int sym)
{
    GibSymHash *s;
    HASH_FIND_INT(hash,&sym,s);
    return (s!=NULL);
}


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Symbol table
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

static GibSym newline_symbol = -1;
static GibSym space_symbol = -1;
static GibSym comma_symbol = -1;
static GibSym leftparen_symbol = -1;
static GibSym rightparen_symbol = -1;


// important! initialize to NULL
GibSymtable *global_sym_table = NULL;

void gib_add_symbol(GibSym idx, char *value)
{
    GibSymtable *s;
    s = gib_alloc(sizeof(GibSymtable));
    s->idx = idx;
    strcpy(s->value, value);
    HASH_ADD(hh, global_sym_table, idx, sizeof(GibSym), s);
    if (idx > gib_global_gensym_counter) {
        gib_global_gensym_counter = idx;
    }
}

inline void gib_set_newline(GibSym idx)
{
    newline_symbol = idx;
    gib_add_symbol(idx,"NEWLINE");
}

inline void gib_set_space(GibSym idx)
{
    space_symbol = idx;
    gib_add_symbol(idx,"SPACE");
}

inline void gib_set_comma(GibSym idx)
{
    comma_symbol = idx;
    gib_add_symbol(idx,"COMMA");
}

inline void gib_set_leftparen(GibSym idx)
{
    leftparen_symbol = idx;
    gib_add_symbol(idx,"LEFTPAREN");
}

inline void gib_set_rightparen(GibSym idx)
{
    rightparen_symbol = idx;
    gib_add_symbol(idx,"RIGHTPAREN");
}

inline int gib_print_symbol(GibSym idx)
{
    if (idx == comma_symbol) {
        return printf(",");
    } else if (idx == newline_symbol) {
        return printf("\n");
    } else if (idx == space_symbol) {
        return printf(" ");
    } else if (idx == leftparen_symbol) {
        return printf("(");
    } else if (idx == rightparen_symbol) {
        return printf(")");
    } else {
        GibSymtable *s;
        HASH_FIND(hh, global_sym_table, &idx, sizeof(GibSym), s);
        if (s == NULL) {
            return printf("%lld", idx);
        } else {
            return printf("%s", s->value);
        }

    }
}

#ifdef _PARALLEL
GibSym gib_gensym()
{
    GibSym idx = __atomic_add_fetch(&gib_global_gensym_counter, 1, __ATOMIC_SEQ_CST);
    return idx;
}
#else
GibSym gib_gensym()
{
    gib_global_gensym_counter += 1;
    GibSym idx = gib_global_gensym_counter;
    return idx;
}
#endif

void gib_free_symtable()
{
    GibSymtable *elt, *tmp;
    HASH_ITER(hh, global_sym_table, elt, tmp) {
        HASH_DEL(global_sym_table,elt);
    }
    free(elt);
    free(tmp);
}

/*

  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Memory Management; regions, chunks, GC etc.
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Gibbon has "growing regions" i.e each logical region is backed by a doubly linked-list
  of smaller chunks which grows as required. In addition to actual data, each chunk
  stores some additional metadata (GibRegionFooter) to chain the chunks together in a list
  and for garbage collection. The footer:

  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  serialized data | rf_reg_metadata_ptr | rf_seq_no | rf_nursery_allocated | rf_size | rf_next | rf_prev
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The metadata after the serialized data serves various purposes:

  - rf_reg_metadata_ptr: A pointer to a GibRegionMeta struct that contains various metadata.
  Of particular interest to us are the fields:

  = reg_id: A unique identifier for a region.

  = refcount and outset: Whenever an inter-region indirection is created, we record that information
  using these two fields. Suppose we have an indirection from region A that points to some chunk
  in region B. Then A's outset will store a pointer to that chunk's footer, and B's refcount will
  be bumped by 1. Note that all there's only 1 refcount cell, and 1 outset per logical region,
  and chunks only store a pointer to them.

  - rf_seq_no: The index of this particular chunk in the list.

  - rf_nursery_allocated: Whether this chunk was allocated in a nursery.

  - rf_size: Used during bounds checking to calculate the size of the next region in
  the linked list.

  - rf_next / rf_prev: Point to the next and previous chunk respectively.


  There are two ways in which a region may be freed:

  (1) Whenever it goes out of scope

  The RTS tries to free a region whenever it goes out of scope. But this doesn't always succeed as
  regions sometimes contain values that "escape". One reason why this'll happen is if there's an
  indirection from A->B, and A lives longer than B.
  In such a case, when B goes out of scope it's refcount won't be 0, and the RTS won't free it.
  This brings us to (2).

  (2)

  When the RTS successfully frees a region, it decrements the refcounts of all the regions it
  points to (via the outset). At the same time, if it encounters a region in the outset whoose
  refcount becomes 0 after the decrement, it calls gib_free_region on that. This way we can be sure
  that all regions will eventually be garbage collected before the program exits.



  Why is it a doubly linked-list?
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Due to way that bounds-checking works, the pointers in the outset may actually point to any
  arbitrary chunk in the chain. However, we must call gib_free_region on the first one to ensure that
  all of them are GC'd. So we need pointers to traverse backward get to the first one.
  'gib_trav_to_first_chunk' accomplishes this.

*/

void gib_insert_into_outset(GibCursor ptr, GibRegionMeta *reg)
{
    uint outset_len = reg->reg_outset_len;
    // Check for duplicates.
    for (uint i = 0; i < outset_len; i++) {
        if (ptr == reg->reg_outset[i]) {
            return;
        }
    }
    // Otherwise, insert into the outset.
    reg->reg_outset[outset_len] = ptr;
    reg->reg_outset_len = outset_len + 1;
    return;
}

void gib_remove_from_outset(GibCursor ptr, GibRegionMeta *reg) {
    uint outset_len = reg->reg_outset_len;
    GibCursor *outset = reg->reg_outset;
    int i;
    if (outset_len == 0) {
        fprintf(stderr, "gib_remove_from_outset: empty outset\n");
        exit(1);
    }
    // Position of 'ptr' in the outset.
    int elt_idx = -1;
    for (i = 0; i < outset_len; i++) {
        if (ptr == outset[i]) {
            elt_idx = i;
        }
    }
    if (elt_idx == -1) {
        fprintf(stderr, "gib_remove_from_outset: element not found\n");
        exit(1);
    }
    // Move all elements ahead of 'elt_idx' back by one position.
    for (i = elt_idx; i < outset_len; i++) {
        outset[i] = outset[i+1];
    }
    return;
}

GibRegionMeta *gib_alloc_region(long long size)
{
    // Allocate the region metadata.
    GibRegionMeta *reg = gib_alloc(sizeof(GibRegionMeta));
    if (reg == NULL) {
        printf("gib_alloc_region: allocation failed: %ld", sizeof(GibRegionMeta));
        exit(1);
    }

    // Allocate the first chunk.
    long long total_size = size + sizeof(GibRegionFooter);
    GibCursor heap;
    bool nursery_allocated = true;
    if (size <= NURSERY_ALLOC_UPPER_BOUND) {
        heap = gib_small_alloc(total_size);
        if (heap == NULL) {
            heap = malloc(total_size);
            nursery_allocated = false;
        }
    } else {
        heap = gib_alloc(total_size);
        nursery_allocated = false;
    }
    if (heap == NULL) {
        printf("gib_alloc_region: malloc failed: %lld", total_size);
        exit(1);
    }
    // Not heap+total_size, since we must keep space for the footer.
    GibCursor heap_end = heap + size;

    // Initialize metadata fields.
    reg->reg_id = gib_gensym();
    reg->reg_refcount = 1;
    reg->reg_heap = heap;
    reg->reg_outset_len = 0;

#ifdef _DEBUG
    printf("Allocated a region(%lld): %lld bytes, nursery=%d.\n", reg->reg_id, size, nursery_allocated);
#endif

    // Write the footer.
    GibRegionFooter *footer = (GibRegionFooter *) heap_end;
    footer->rf_reg_metadata_ptr = reg;
    footer->rf_seq_no = 1;
    footer->rf_nursery_allocated = nursery_allocated;
    footer->rf_size = size;
    footer->rf_next = NULL;
    footer->rf_prev = NULL;

    return reg;
}

inline GibRegionMeta *gib_alloc_counted_region(long long size)
{
    // Bump the count.
    gib_bump_global_region_count();
    return gib_alloc_region(size);
}

GibChunk gib_alloc_chunk(GibCursor end_old_chunk)
{
    // Get size from current footer.
    GibRegionFooter *footer = (GibRegionFooter *) end_old_chunk;
    long long newsize = footer->rf_size * 2;
    // See #110.
    if (newsize > gib_global_max_chunk_size) {
        newsize = gib_global_max_chunk_size;
    }
    long long total_size = newsize + sizeof(GibRegionFooter);

    // Allocate.
    GibCursor start = gib_alloc(total_size);
    if (start == NULL) {
        printf("gib_alloc_chunk: malloc failed: %lld", total_size);
        exit(1);
    }
    GibCursor end = start + newsize;

    // Link the next chunk's footer.
    footer->rf_next = (GibRegionFooter *) end;

    // Write the footer.
    GibRegionFooter* new_footer = (GibRegionFooter *) end;
    new_footer->rf_reg_metadata_ptr = footer->rf_reg_metadata_ptr;
    new_footer->rf_seq_no = footer->rf_seq_no + 1;
    new_footer->rf_nursery_allocated = false;
    new_footer->rf_size = newsize;
    new_footer->rf_next = NULL;
    new_footer->rf_prev = footer;

#ifdef _DEBUG
    GibRegionMeta *reg = (GibRegionMeta*) new_footer->rf_reg_metadata_ptr;
    printf("gib_alloc_chunk: allocated %lld bytes for region %lld.\n", total_size, reg->reg_id);
#endif

    return (GibChunk) {start , end};
}

GibRegionFooter *gib_trav_to_first_chunk(GibRegionFooter *footer)
{
    if (footer->rf_seq_no == 1) {
        return footer;
    } else if (footer->rf_prev == NULL) {
        fprintf(stderr, "No previous chunk found at rf_seq_no: %lld", footer->rf_seq_no);
        return NULL;
    } else {
        gib_trav_to_first_chunk((GibRegionFooter *) footer->rf_prev);
    }
    return NULL;
}

inline uint gib_get_ref_count(GibCursor end_ptr)
{
    GibRegionFooter *footer = (GibRegionFooter *) end_ptr;
    GibRegionMeta *reg = (GibRegionMeta *) footer->rf_reg_metadata_ptr;
    return reg->reg_refcount;
}

// B is the pointer, and A is the pointee (i.e B -> A).
// Bump A's refcount and update B's outset.
inline void gib_bump_refcount(GibCursor end_b, GibCursor end_a)
{
    if (end_a == end_b) {
#ifdef _DEBUG
        printf("gib_bump_refcount: indirection within a region found, refcount not bumped. TODO.\n");
#endif
        return;
    }
    // Grab footers.
    GibRegionFooter *footer_a = (GibRegionFooter *) end_a;
    GibRegionFooter *footer_b = (GibRegionFooter *) end_b;

    // Grab metadata.
    GibRegionMeta *reg_a = (GibRegionMeta *) footer_a->rf_reg_metadata_ptr;
    GibRegionMeta *reg_b = (GibRegionMeta *) footer_b->rf_reg_metadata_ptr;

    // Bump A's refcount.
    uint current_refcount, new_refcount;
    current_refcount = reg_a->reg_refcount;
    new_refcount = current_refcount + 1;
    reg_a->reg_refcount = new_refcount;

#ifdef _DEBUG
    printf("gib_bump_refcount: %lld -> %lld\n", reg_b->reg_id, reg_a->reg_id);
    printf("gib_bump_refcount: old-refcount=%d, old-outset-len=%d:\n", current_refcount, reg_b->reg_outset_len);
    assert(current_refcount == reg_b->reg_outset_len+1);
#endif

    // Add A to B's outset.
    gib_insert_into_outset(end_a, reg_b);

#ifdef _DEBUG
    // printf("gib_bump_refcount: Added %p to %lld's outset, %p.\n", end_a, reg_b->reg_id, reg_b);
    printf("gib_bump_refcount: new-refcount=%d, new-outset-len=%d\n", new_refcount, reg_b->reg_outset_len);
    assert(new_refcount == reg_b->reg_outset_len+1);
#endif

    return;
}

void gib_free_region(GibCursor end_reg) {
    // Grab footer and the metadata.
    GibRegionFooter *footer = (GibRegionFooter *) end_reg;
    GibRegionMeta *reg = (GibRegionMeta *) footer->rf_reg_metadata_ptr;

    //
    GibRegionFooter *first_chunk_footer, *next_chunk_footer;
    GibCursor first_chunk, next_chunk;

    // Decrement current reference count.
    uint current_refcount, new_refcount;
    current_refcount = reg->reg_refcount;
    new_refcount = 0;
    if (current_refcount != 0) {
        new_refcount = current_refcount - 1;
        reg->reg_refcount = new_refcount;
    }

#ifdef _DEBUG
    printf("gib_free_region(%lld): refcounts (1): old-refcount=%d, new-refcount=%d:\n", reg->reg_id, current_refcount, new_refcount);
#endif


    // Free this region recount is 0.
    if (new_refcount == 0) {

#ifdef _DEBUG
        printf("gib_free_region(%lld): outset length: %d\n", reg->reg_id, reg->reg_outset_len);
#endif

        // Decrement refcounts, free regions with refcount==0 and also free
        // elements of the outset.
        if (reg->reg_outset_len != 0) {
            uint outset_len = reg->reg_outset_len;
            GibCursor *outset = reg->reg_outset;
            GibRegionFooter *elt_footer;
            GibRegionMeta *elt_reg;
            uint elt_current_refcount, elt_new_refcount;
            GibCursor to_be_removed[MAX_OUTSET_LENGTH];
            uint to_be_removed_idx = 0;
            for (int i = 0; i < outset_len; i++) {
                elt_footer = (GibRegionFooter *) outset[i];
                elt_reg = (GibRegionMeta *) elt_footer->rf_reg_metadata_ptr;
#ifdef _DEBUG
                elt_current_refcount = elt_reg->reg_refcount;
#endif
                elt_new_refcount = elt_current_refcount - 1;
                elt_reg->reg_refcount = elt_new_refcount;
#ifdef _DEBUG
                printf("gib_free_region(%lld): old-refcount=%d, new-refcount=%d:\n",
                       elt_reg->reg_id, elt_current_refcount, elt_reg->reg_refcount);
#endif
                if (elt_new_refcount == 0) {
                    // See [Why is it a doubly linked-list?] above
                    first_chunk_footer = gib_trav_to_first_chunk(elt_footer);
                    if (first_chunk_footer != NULL) {
                        gib_free_region((GibCursor) first_chunk_footer);
                    }
                }
                to_be_removed[to_be_removed_idx] = outset[i];
                to_be_removed_idx++;
            }
            // Remove elements from the outset.
            for (uint i = 0; i < to_be_removed_idx; i++) {
                gib_remove_from_outset(to_be_removed[i], reg);
            }
        }


#ifdef _DEBUG
        // Bookkeeping
        long long num_freed_chunks = 0, total_bytesize = 0;
#endif

        // Free the chunks in this region.
        first_chunk = end_reg - footer->rf_size;
        first_chunk_footer = footer;
        next_chunk = (char*) footer->rf_next;

#ifdef _DEBUG
        printf("gib_free_region(%lld): first chunk in nursery: %d\n",
               reg->reg_id,
               first_chunk_footer->rf_nursery_allocated);
#endif

        if (! first_chunk_footer->rf_nursery_allocated) {
#ifdef _DEBUG
            num_freed_chunks++;
            total_bytesize = total_bytesize + first_chunk_footer->rf_size;
#endif
            free(first_chunk);
        }

        while (next_chunk != NULL) {
            next_chunk_footer = (GibRegionFooter *) next_chunk;
#ifdef _DEBUG
            num_freed_chunks++;
            total_bytesize = total_bytesize + next_chunk_footer->rf_size;
#endif
            free(next_chunk - next_chunk_footer->rf_size);
            next_chunk = (char*) next_chunk_footer->rf_next;
        }

#ifdef _DEBUG
        printf("gib_free_region(%lld): Freed %lld bytes across %lld chunks.\n",
               reg->reg_id, total_bytesize, num_freed_chunks);
#endif

        // Free the metadata.
        free(reg);

    } else {
#ifdef _DEBUG
        printf("gib_free_region(%lld): non-zero refcount: %d.\n",
               reg->reg_id, reg->reg_refcount);
#endif
    }
}

// Assume that all nodes with size information have tags >= 150.
GibBool gib_is_big(GibInt i, GibCursor cur)
{
    GibPackedTag tag = *(GibPackedTag *) cur;
    if (tag >= 150) {
        cur += 1;
        GibInt size = *(GibInt *) cur;
        if (size >= i) {
            return true;
        } else {
            return false;
        }
    }
    return false;
}

#ifdef _PARALLEL
void gib_bump_global_region_count()
{
    __atomic_add_fetch(&gib_global_region_count, 1, __ATOMIC_SEQ_CST);
    return;
}
#else
void gib_bump_global_region_count()
{
    gib_global_region_count++;
    return;
}
#endif

void gib_print_global_region_count()
{
    printf("REGION_COUNT: %lld\n", gib_global_region_count);
    return;
}


/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Vectors
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

GibVector *gib_vector_alloc(GibInt num, size_t elt_size)
{
    GibVector *vec = gib_alloc(sizeof(GibVector));
    if (vec == NULL) {
        printf("alloc_vector: malloc failed: %ld", sizeof(GibVector));
        exit(1);
    }
    void* data = gib_alloc(num * elt_size);
    if (data == NULL) {
        printf("alloc_vector: malloc failed: %ld", sizeof(num * elt_size));
        exit(1);
    }
    vec->vec_lower = 0;
    vec->vec_upper = num;
    vec->vec_elt_size = elt_size;
    vec->vec_data = data;
    return vec;
}

inline GibInt gib_vector_length(GibVector *vec)
{
    return (vec->vec_upper - vec->vec_lower);
}

inline GibBool gib_vector_is_empty(GibVector *vec)
{
    return (gib_vector_length(vec) == 0);
}

GibVector *gib_vector_slice(GibInt i, GibInt n, GibVector *vec)
{
    GibInt lower = vec->vec_lower + i;
    GibInt upper = vec->vec_lower + i + n;
    if ((lower > vec->vec_upper)) {
        printf("gib_vector_slice: lower out of bounds, %lld > %lld", lower, vec->vec_upper);
        exit(1);
    }
    if ((upper > vec->vec_upper)) {
        printf("gib_vector_slice: upper out of bounds: %lld > %lld", upper, vec->vec_upper);
        exit(1);
    }
    GibVector *vec2 = gib_alloc(sizeof(GibVector));
    if (vec == NULL) {
        printf("gib_vector_slice: malloc failed: %ld", sizeof(GibVector));
        exit(1);
    }
    vec2->vec_lower = lower;
    vec2->vec_upper = upper;
    vec2->vec_elt_size = vec->vec_elt_size;
    vec2->vec_data = vec->vec_data;
    return vec2;
}

// The callers must cast the return value.
inline void *gib_vector_nth(GibVector *vec, GibInt i)
{
    // if (i < vec->lower || i > vec->upper) {
    //     printf("gib_vector_nth index out of bounds: %lld (%lld,%lld) \n", i, vec->vec_lower, vec->vec_upper);
    //     exit(1);
    // }
    return (vec->vec_data + (vec->vec_elt_size * (vec->vec_lower + i)));
}

inline GibVector *gib_vector_inplace_update(GibVector *vec, GibInt i, void* elt)
{
    void* dst = gib_vector_nth(vec, i);
    memcpy(dst, elt, vec->vec_elt_size);
    return vec;
}

inline GibVector *gib_vector_copy(GibVector *vec)
{
    GibInt len = gib_vector_length(vec);
    void *start = gib_vector_nth(vec, 0);
    GibVector *vec2 = gib_vector_alloc(len, vec->vec_elt_size);
    memcpy(vec2->vec_data, start, len * vec->vec_elt_size);
    return vec2;
}

inline GibVector *gib_vector_inplace_sort(GibVector *vec, int (*compar)(const void *, const void*))
{
    void *start = gib_vector_nth(vec, 0);
    qsort(start, gib_vector_length(vec), vec->vec_elt_size, compar);
    return vec;
}

inline GibVector *gib_vector_sort(GibVector *vec, int (*compar)(const void *, const void*))
{
    GibVector *vec2 = gib_vector_copy(vec);
    gib_vector_inplace_sort(vec2, compar);
    return vec2;
}

GibVector *gib_vector_concat(GibVector *vec)
{
    // Length of the input vector.
    GibInt len = gib_vector_length(vec);
    // Length of the concatenated vector.
    GibInt result_len = 0;
    // Size of each element in the concatenated vector.
    GibInt result_elt_size = 0;
    GibVector **elt_ref, *elt;
    for (GibInt i = 0; i < len; i++) {
        elt_ref = gib_vector_nth(vec, i);
        elt = *elt_ref;
        result_elt_size = elt->vec_elt_size;
        result_len += gib_vector_length(elt);
    }

    // Concatenated vector.
    GibVector *result = gib_vector_alloc(result_len, result_elt_size);
    GibInt elt_len;
    // A counter that tracks the index of elements in 'result'.
    GibInt k = 0;
    for (GibInt i = 0; i < len; i++) {
        elt_ref = gib_vector_nth(vec, i);
        elt = *elt_ref;
        elt_len = gib_vector_length(elt);

        for (GibInt j = 0; j < elt_len; j++) {
            void* k_elt = gib_vector_nth(elt, j);
            gib_vector_inplace_update(result, k, k_elt);
            k++;
        }
    }

    return result;
}

inline void gib_vector_free(GibVector *vec)
{
    free(vec->vec_data);
    free(vec);
    return;
}

GibVector *gib_vector_merge(GibVector *vec1, GibVector *vec2)
{
    if (vec1->vec_upper != vec2->vec_lower) {
        printf("gib_vector_merge: non-contiguous slices, (%lld,%lld), (%lld,%lld).",
               vec1->vec_lower, vec1->vec_upper, vec2->vec_lower, vec2->vec_upper);
        exit(1);
    }
    GibVector *merged = gib_alloc(sizeof(GibVector));
    if (merged == NULL) {
        printf("gib_vector_merge: malloc failed: %ld", sizeof(GibVector));
        exit(1);
    }
    merged->vec_lower = vec1->vec_lower;
    merged->vec_upper = vec2->vec_upper;
    merged->vec_elt_size = vec1->vec_elt_size;
    merged->vec_data = vec1->vec_data;
    return merged;
}

void gib_print_timing_array(GibVector *times) {
    printf("TIMES: [");
    double *d;
    GibInt n = gib_vector_length(times);
    for(GibInt i = 0; i < n; i++) {
        d = gib_vector_nth(times, i);
        if (i == (n-1)) {
            printf("%f",*d);
        }
        else {
            printf("%f, ",*d);
        }
    }
    printf("]\n");
}

double gib_sum_timing_array(GibVector *times)
{
    double *d;
    double acc = 0;
    for(int i = 0; i < gib_vector_length(times); i++) {
        d = gib_vector_nth(times, i);
        acc += *d;
    }
    return acc;
}

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Linked lists
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

inline GibList *gib_list_alloc(size_t data_size)
{
    // GibList *ls = gib_alloc(sizeof(GibList));
    GibList *ls = gib_bumpalloc(sizeof(GibList));
    ls->ll_data_size = data_size;
    ls->ll_data = NULL;
    ls->ll_next = NULL;
    return ls;
}

inline GibBool gib_list_is_empty(GibList *ls)
{
    return ls->ll_next == NULL;
}

inline GibList *gib_list_cons(void *elt, GibList *ls)
{
    // void* data = gib_alloc(ls->data_size);
    void* data = gib_bumpalloc(ls->ll_data_size);
    if (data == NULL) {
        printf("gib_list_cons: malloc failed: %ld", ls->ll_data_size);
        exit(1);
    }
    memcpy(data, elt, ls->ll_data_size);
    // GibList *res = gib_alloc(sizeof(GibList));
    GibList *res = gib_bumpalloc(sizeof(GibList));
    res->ll_data_size = ls->ll_data_size;
    res->ll_data = data;
    res->ll_next = (GibList*) ls;
    return res;
}

inline void *gib_list_head(GibList *ls)
{
    return ls->ll_data;
}

inline GibList* gib_list_tail(GibList *ls)
{
    return ls->ll_next;
}

inline void gib_list_free(GibList *ls)
{
    free(ls->ll_data);
    free(ls);
    return;
}

inline GibList *gib_list_copy(GibList *ls)
{
    GibList *ls2 = gib_list_alloc(ls->ll_data_size);
    if (ls->ll_data != NULL) {
        void* data = gib_bumpalloc(ls->ll_data_size);
        memcpy(data, ls->ll_data, ls->ll_data_size);
        ls2->ll_data = data;
    }
    ls2->ll_next = ls->ll_next;
    return ls2;
}

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Ppm images
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

// Example: writePpm("gibbon_rgb_1000.ppm", 1000, 1000, pixels);
void gib_write_ppm(char* filename, GibInt width, GibInt height, GibVector *pixels) {
    FILE *fp;
    fp = fopen(filename, "w+");
    fprintf(fp, "P3\n");
    fprintf(fp, "%lld %lld\n255\n", width, height);
    GibInt len = gib_vector_length(pixels);
    gib_write_ppm_loop(fp, 0, len, pixels);
    fclose(fp);
    return;
}

void gib_write_ppm_loop(FILE *fp, GibInt idx, GibInt end, GibVector *pixels) {
    bool fltIf_5768_6575 = idx == end;

    if (fltIf_5768_6575) {
        return;
    } else {
        GibPixel *tmp_112;
        tmp_112 = (GibPixel *) gib_vector_nth(pixels, idx);
        GibPixel tup = *tmp_112;
        GibInt x = tup.field0;
        GibInt y = tup.field1;
        GibInt z = tup.field2;
        // write to file.
        fprintf(fp, "%lld %lld %lld\n", x, y, z);
        gib_write_ppm_loop(fp, (idx+1), end, pixels);
    }
}

/* ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Main functions
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */

int main(int argc, char** argv)
{
    // parameters to parse:
    //
    //   num iterations: How many times to repeat a benchmark.
    //   tree size: An integer passes to `build_tree()`.

    struct rlimit lim;
    int code;
    if ( (code = getrlimit(RLIMIT_STACK, &lim)) ) {
        fprintf(stderr, " [gibbon rts] failed to getrlimit, code %d\n", code);
        exit(1);
    }

    // lim.rlim_cur = 1024LU * 1024LU * 1024LU; // 1GB stack.
    lim.rlim_cur = 512LU * 1024LU * 1024LU; // 500MB stack.
    // lim.rlim_max = lim.rlim_cur; // Normal users may only be able to decrease this.

    // WARNING: Haven't yet figured out why this doesn't work on MacOS...
#ifndef __APPLE__
    code = setrlimit(RLIMIT_STACK, &lim);
    while (code) {
        fprintf(stderr, " [gibbon rts] Failed to set stack size to %llu, code %d\n", (unsigned long long)lim.rlim_cur, code);
        lim.rlim_cur /= 2;
        // lim.rlim_max /= 2;
        if(lim.rlim_cur < 100 * 1024) {
            fprintf(stderr, " [gibbon rts] Failed setrlimit stack size to something reasonable; giving up.\n");
            break; // abort();
        }
        int code = setrlimit(RLIMIT_STACK, &lim);
    }
#endif

    int got_numargs = 0; // How many numeric arguments have we got.

    int i;
    for (i = 1; i < argc; ++i)
    {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            gib_show_usage(argv);
            exit(0);
        }
        else if (strcmp(argv[i], "--biginf-buffer-size") == 0 && i < argc - 1)
        {
            gib_global_biginf_init_chunk_size = atoll(argv[i + 1]);
            i++;
        }
        else if (strcmp(argv[i], "--inf-buffer-size") == 0 && i < argc - 1)
        {
            gib_global_inf_init_chunk_size = atoll(argv[i + 1]);
            i++;
        }
        else if ((strcmp(argv[i], "--bench-input") == 0)) {
            if (i+1 >= argc) {
                fprintf(stderr, "Not enough arguments after --bench-input, expected <file>.\n");
                gib_show_usage(argv);
                exit(1);
            }
            gib_global_benchfile_param = argv[i+1];
            i++;
        }
        else if ((strcmp(argv[i], "--array-input") == 0)) {
            if (i+1 >= argc) {
                fprintf(stderr, "Not enough arguments after --array-input, expected <file>.\n");
                gib_show_usage(argv);
                exit(1);
            }
            gib_global_arrayfile_param = argv[i+1];
            i++;
        }
        else if (strcmp(argv[i], "--array-input-length") == 0 && i < argc - 1) {
            gib_global_arrayfile_length_param = atoll(argv[i+1]);
            i++;
        }
        else if (strcmp(argv[i], "--bench-prog") == 0 && i < argc - 1) {
            int len = strlen(argv[i+1]);
            gib_global_bench_prog_param = (char*) malloc((len+1)*sizeof(char));
            strncpy(gib_global_bench_prog_param,argv[i+1],len);
            i++;
        }
        // If present, we expect the two arguments to be <size> <iters>
        else if (got_numargs >= 2) {
            fprintf(stderr, "Extra arguments left over: ");
            for(; i < argc; i++) fprintf(stderr, "%s ", argv[i]);
            gib_show_usage(argv);
            exit(1);
        } else {
            if (got_numargs == 0) {
                gib_global_size_param  = atoll(argv[i]);
                got_numargs ++;
            } else {
                gib_global_iters_param = atoll(argv[i]);
            }
        }
    }

    // Initialize gib_global_bench_prog_param to an empty string in case
    // the runtime argument --bench-prog isn't passed.
    if (gib_global_bench_prog_param == NULL) {
        gib_global_bench_prog_param = (char*) malloc(1*sizeof(char));
        *gib_global_bench_prog_param = '\n';
    }

    gib_main_expr();

    // // Test linking with the new Rust RTS.
    // hello_rust();

    return 0;
}
